image: node:12

build_npm:
    stage: build
    script:
        - git config --global url."git@github.com:".insteadOf https://github.com/
        - git config --global url."git://".insteadOf https://
        - npm ci --dev
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - node_modules/
        policy: push
    only:
        refs:
            - master
            - dev
            - dev-rwTS
        changes:
            - .gitlab-ci.yml
            - package.json
            - package-lock.json

test_jest:
    stage: test
    script:
        - npm run test
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - node_modules/
        policy: pull
    only:
        - master
        - dev
        - dev-rwTS

deploy:
    stage: deploy
    script:
        - npm run build-prod
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - node_modules/
        policy: pull
    artifacts:
        name: "redwarn-$CI_COMMIT_REF_NAME"
        paths:
            - build/
    only:
        - master
        - dev
        - dev-rwTS
